#application-local
server:
  port: 8080

spring:
  application:
    name: talkstream

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: prometheus
